Asp.NetMVCCrud/Models/DbModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Asp.NetMVCCrud.Models
{
    public enum Course { ESAD=1, DDD,NT,GAVE, JAVA}
    public class Batch
    {
        public int BatchId { get; set; }
        [Required, StringLength(50), Display(Name ="Batch Code")]
        public string BatchCode { get; set; }
        [EnumDataType(typeof(Course))]
        public Course Course { get;set; }
        [Required]
        public int Round { get; set; }
        [Required, Column(TypeName ="date"), Display(Name ="Start Date"), DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime StartDate { get; set; }
        [Column(TypeName ="date"), Display(Name ="End Date"), DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public DateTime? EndDate { get; set; }
        [Display(Name ="Complete?")]
        public bool IsComplete { get; set; }

    }
    public class BatchDbContext: DbContext
    {
        public DbSet<Batch> Batches { get; set;}
    }
    
}

Asp.NetMVCCrud/Controllers/BatchesController.cs
using Asp.NetMVCCrud.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVCCrud.Controllers
{
    public class BatchesController : Controller
    {
        BatchDbContext db = new BatchDbContext();
        // GET: Batches
        public ActionResult Index()
        {
            return View(db.Batches.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Batch b)
        {
            if(ModelState.IsValid)
            {
                db.Batches.Add(b);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View(db.Batches.First(b=>b.BatchId == id));
        }
        [HttpPost]
        public ActionResult Edit(Batch b)
        {
            if (ModelState.IsValid)
            {
                db.Entry(b).State =EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(b);
        }
        public ActionResult Delete(int id)
        {
            return View(db.Batches.First(b => b.BatchId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DoDelete(int id)
        {
            Batch b = new Batch { BatchId= id };
            db.Entry(b).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Asp.NetMVCCrud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Asp.NetMVCCrud.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Asp.NetMVCCrud/Views/Batches/Create.cshtml
@model Asp.NetMVCCrud.Models.Batch
@{
    ViewBag.Title = "Create";
}
<div class="row">
    <div class="col-12">
        <h3>Add Batches</h3>
        @using (Html.BeginForm("Create", "Batches", FormMethod.Post, new { }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BatchCode, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.BatchCode, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.BatchCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Round, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Round, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Round, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Course, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.EnumDropDownListFor(x => x.Course, new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.Course, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.IsComplete, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.CheckBoxFor(x => x.IsComplete, new { @class = "form-check form-check-sm" })
                    @Html.ValidationMessageFor(x => x.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button> 
                </div>
            </div>
        }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to List", "Index")
</div>

Asp.NetMVCCrud/Views/Batches/Delete.cshtml
@model Asp.NetMVCCrud.Models.Batch
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3> Confrim Delete</h3>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BatchCode, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.BatchCode, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Round, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.Round, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Course, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.Course, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.StartDate, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.EndDate, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.IsComplete, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.DisplayFor(x => x.IsComplete, new { @class = "form-control form-control-sm" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @using (Html.BeginForm())
            {
                @Html.HiddenFor(x=>x.BatchId)
            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>
            </div>
            }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to list", "Index")
</div>

Asp.NetMVCCrud/Views/Batches/Edit.cshtml
@model Asp.NetMVCCrud.Models.Batch
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <h3>Edit Batches</h3>
        @using (Html.BeginForm("Edit", "Batches", FormMethod.Post, new { }))
        {
            @Html.HiddenFor(x=>x.BatchId)
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BatchCode, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.BatchCode, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.BatchCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Round, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Round, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.Round, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Course, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.EnumDropDownListFor(x => x.Course, new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.Course, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.IsComplete, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.CheckBoxFor(x => x.IsComplete, new { @class = "form-check form-check-sm" })
                    @Html.ValidationMessageFor(x => x.IsComplete, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>
<div class="col-12">
    @Html.ActionLink("Back to List", "Index")
</div>

Asp.NetMVCCrud/Views/Batches/Index.cshtml
@model IEnumerable<Asp.NetMVCCrud.Models.Batch>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Batches</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add New", "Create", "Batches", new { }, new {@class= "btn btn-primary btn-sm"})
        </div> 
        <table class="table table-bordered">
            <thead class="bg-light">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.BatchCode)</th>
                    <th>@Html.DisplayNameFor(x => x.Round)</th>
                    <th>@Html.DisplayNameFor(x => x.Course)</th>
                    <th>@Html.DisplayNameFor(x => x.StartDate)</th>
                    <th>@Html.DisplayNameFor(x => x.EndDate)</th>
                    <th>@Html.DisplayNameFor(x => x.IsComplete)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                <tr>
                    <td>@Html.DisplayFor(x => b.BatchCode)</td>
                    <td>@Html.DisplayFor(x => b.Round)</td>
                    <td>@Html.DisplayFor(x => b.Course)</td>
                    <td>@Html.DisplayFor(x => b.StartDate)</td>
                    <td>@Html.DisplayFor(x => b.EndDate)</td>
                    <td>@Html.DisplayFor(x => b.IsComplete)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Batches", new { id = b.BatchId }, new { @class = "btn btn-secondary btn-sm" })
                        <a href="@Url.Action("Delete", "Batches", new { id = b.BatchId }) " class="btn btn-danger btn-sm">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table> 
    </div>
</div>

Asp.NetMVCCrud/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Asp.NetMVCCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.3.js"></script>
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar navbar-light bg-light navbar-expand-md  shadow-sm">
        <div class="container-fluid">
            <span class="navbar-brand">MVC 5</span>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav nav ms-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Batches", "Index", "Batches", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <section class="container-fluid main">
        @RenderBody()
    </section> 
    @RenderSection("scripts", false)
</body>
</html>